Update welcome-to-d.md
dlang-tour/german pull request #18
Opened 2017-05-28 23:17 UTC by SMietzner

Hi! Bin neu hier und dachte ich bring mich mal ein bischen ein und helfe bei der Übersetzung der Tour...

2017-05-28 23:22 UTC, wilzbach requested changes
Wow. Vielen Dank! Jede Hilfe ist selbstverständlich gerne willkommen :)

Ich habe noch eine kleine Anmerkung, aber ansonsten ist alles LGTM.

2017-05-28 23:22 UTC, wilzbach commented on welcome/welcome-to-d.md
> +    // dem Stichwort "Range algorithms"
Ich würde das auch übersetzen, z.B. Range-Algorithmus oder einfach nur "Ranges"

2017-05-28 23:43 UTC, SMietzner commented
Mal 'ne Frage: Was hat es mit den " The Travis CI build failed" auf sich?

2017-05-29 00:04 UTC, wilzbach approved these changes

2017-05-29 00:07 UTC, wilzbach commented
> Mal 'ne Frage: Was hat es mit den "The Travis CI build failed" auf sich?

```
object.Exception@source/contentprovider.d(288): Source code line length exceeds 48 limit in 'Willkommen zu D':     // Mehr über dieses Beispiel findest du unter 
```

Da die Tour auch für mobile Endgeräte ausgelegt ist, ist die maximal erlaubte Länge der Quellcode-Beispiele 48 Zeichen. In Vim kannst du dir das per `set cc=48` anzeigen lassen.

2017-05-29 03:50 UTC, wilzbach commented
Thanks a lot!
Btw you also can run the sanitycheck locally, e.g. in your folder `dub run dlang-tour -- -l . --sanitycheck`

2017-05-29 03:51 UTC, merged